---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 120m
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: linkerd
    metricsServer: http://prometheus-operator-kube-p-prometheus.monitoring:9090

